#!/usr/bin/env bash
# transfers a file from our client to a server

"$1"=filepath
"$2"=ipaddrs
"$3"=username
"$4"=sshkey_path

if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi