#!/usr/bin/env bash
# Installs nginx and set a default messasge
# port 80 as a default

sudo apt update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
