#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

sudo apt update -y && \
sudo apt install -y nginx

if [ "$#" -eq 0 ]
then
    echo -e \
"http {
    root /var/www/html;
    index index.html;
    server {
        listen 80;
        location \ {
        }
    }
}
events {
}" > /etc/nginx/nginx.conf
    mkdir -p /var/www/html
    echo "Hello World!" > \
        /var/www/html/index.html
    sudo service nginx start
    if [ "$#" -ne 0 ]
    then
        "Problem starting nginx"
        exit 1
    fi
else
    echo "Could not install nginx"
    exit 1
fi
exit 0
