#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt update -y && \
sudo apt install -y nginx

if [ "$#" -eq 0 ]
then
    echo -e \
"http {
    root /var/www/100.27.12.14/html;
    index index.html index.htm index.nginx-debian.html;
    server {
        listen 80;
	listen [::]:80;
	location / {
		 try_files $uri $uri/ =404;
	}
        location /redirect_me {
		 return 301 http://github.com/Okinbird;
        }
    }
}
events {
}" > /etc/nginx/sites-enabled/100.27.12.14
    mkdir -p /var/www/100.27.12.14/html
    echo "Hello World!" > \
        /var/www/100.27.12.14/html/index.html
    sudo service nginx start
    if [ "$#" -ne 0 ]
    then
        "Problem starting nginx"
        exit 1
    fi
else
    echo "Could not install nginx"
    exit 1
fi
exit 0
