#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt update
sudo apt install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
printf %s "server {
       listen 80;
       listen [::]:80 default_server;
       root   /var/www/html;
       index  index.html index.htm;
       location /redirect_me {
       		return 301 http://github.com/Okinbird;
       }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
