#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#+     at the root with a curl GET request.
#+    Configures /redirect_me as a "301 Moved Permanently".
#+    Includes a custom 404 page containing "Ceci n'est pas une page".
#+    Contains a custom HTTP header named X-Served-By.
#+    The value of the HTTP header is the hostname of the running server.

sudo apt update
sudo apt install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
printf %s "server {
       listen 80;
       listen [::]:80 default_server;
       root   /var/www/html;
       index  index.html index.htm;
       location / {
             add_header X-Served-By $HOSTNAME;
             try_files $uri $uri/ =404;
       }
       location /redirect_me {
       		return 301 http://github.com/Okinbird;
       }
       error_page 404 /404.html;
       location /404 {
       root /var/www/html;
       internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
