#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt install -y software-properties-common
sudo add-repository -y ppa:vbernat/haproxy
sudo apt update
sudo apt install -y haproxy

echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
       log 127.0.0.1 local0 notice
       maxconn 2000
       user haproxy
       group haproxy
defaults
       log     global
       mode    http
       option  httplog
       option  dontlognull
       retries 3
       option redispatch
       timeout connect  5000
       timeout client  10000
       timeout server  10000
listen Okinbird
       bind 0.0.0.0:80
       mode http
       stats enable
       stats uri /haproxy?stats
       balance roundrobin
       option httpclose
       option forwardfor
       server Okinbird-web-01 100.27.12.14:80 check
       server Okinbird-web-02 100.26.233.174:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
