#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -1)"

