#!/usr/bin/env bash
# A Bash (init) script that manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"


PROGRAM='manage_my_process'
RELPATH="${0%/*}/${PROGRAM}"
PIDFILE="${PIDFILE:-/var/run/my_process.pid}"
declare -A MESSAGES=(
    ['start']='started'
    ['stop']='stopped'
    ['restart']='restarted'
)

start() {
    exec -- "${RELPATH}" &
    echo "$!" >| "${PIDFILE}"
}

stop() {
    trap '
      trap RETURN
      rm -f -- "${PIDFILE}"
    ' RETURN
    kill -- "$(< "${PIDFILE}")" 2> /dev/null
}

restart() {
    stop
    start
}

if (( $# == 1 )) && [[ -v "MESSAGES[$1]" ]]
then
    "$1" && printf '%s %s\n' "${PROGRAM}" "${MESSAGES[$1]}"
else
    printf 'Usage: %s {start|stop|restart}\n' "${PROGRAM}"
    exit 1
fi
