#!/usr/bin/env bash
# Using while loop, this script displays the content of the file /etc/passwd
# Display username
# Display user id
# Display Home directory path for the user

while read passwd;
do
    echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"