#!/usr/bin/env bash
# Using while loop and case statement
# This script loops from 1 to 20
# the 4th iteration, displays 4 and then bad luck from China
# the 9th iteration, displays 9 and then bad luck from Japan
# the 17th iteration, displays 17 and then bad luck from Italy
# displays numbers for the other iterations

counter=1

while [ $counter -le 20 ]
do
    echo "$counter"
    case $counter in
        "4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
    esac
    (( counter++ ))
done