#!/usr/bin/env bash
# Using for loop statement
# This script loops the contents in the current directory 
# Displays the content of the current directory
# Displays in a list format
# Displays where only the part of the name after the first dash is displayed

list=$(ls)
for i in $list;
do
    echo "$i" | cut -d '-' -f2
done